        tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "on-secondary-fixed-variant": "var(--c-on-secondary-fixed-variant)",
                        "inverse-primary": "var(--c-inverse-primary)",
                        "error": "var(--c-error)",
                        "on-secondary": "var(--c-on-secondary)",
                        "background": "var(--c-background)",
                        "inverse-surface": "var(--c-inverse-surface)",
                        "deep-navy": "var(--c-deep-navy)",
                        "secondary-fixed": "var(--c-secondary-fixed)",
                        "on-primary-fixed-variant": "var(--c-on-primary-fixed-variant)",
                        "on-surface-variant": "var(--c-on-surface-variant)",
                        "warning": "var(--c-warning)",
                        "on-surface": "var(--c-on-surface)",
                        "surface-container-highest": "var(--c-surface-container-highest)",
                        "on-primary-fixed": "var(--c-on-primary-fixed)",
                        "tertiary": "var(--c-tertiary)",
                        "surface-container-low": "var(--c-surface-container-low)",
                        "tertiary-fixed": "var(--c-tertiary-fixed)",
                        "on-primary": "var(--c-on-primary)",
                        "slate-gray": "var(--c-slate-gray)",
                        "surface-tint": "var(--c-surface-tint)",
                        "tertiary-container": "var(--c-tertiary-container)",
                        "on-tertiary-fixed-variant": "var(--c-on-tertiary-fixed-variant)",
                        "secondary": "var(--c-secondary)",
                        "on-tertiary-fixed": "var(--c-on-tertiary-fixed)",
                        "success": "var(--c-success)",
                        "secondary-container": "var(--c-secondary-container)",
                        "surface-container-lowest": "var(--c-surface-container-lowest)",
                        "on-tertiary-container": "var(--c-on-tertiary-container)",
                        "on-background": "var(--c-on-background)",
                        "inverse-on-surface": "var(--c-inverse-on-surface)",
                        "on-primary-container": "var(--c-on-primary-container)",
                        "outline": "var(--c-outline)",
                        "on-error": "var(--c-on-error)",
                        "surface-container-high": "var(--c-surface-container-high)",
                        "primary-container": "var(--c-primary-container)",
                        "on-tertiary": "var(--c-on-tertiary)",
                        "on-secondary-container": "var(--c-on-secondary-container)",
                        "surface": "var(--c-surface)",
                        "on-error-container": "var(--c-on-error-container)",
                        "secondary-fixed-dim": "var(--c-secondary-fixed-dim)",
                        "on-secondary-fixed": "var(--c-on-secondary-fixed)",
                        "outline-variant": "var(--c-outline-variant)",
                        "surface-bright": "var(--c-surface-bright)",
                        "tertiary-fixed-dim": "var(--c-tertiary-fixed-dim)",
                        "primary": "var(--c-primary)",
                        "primary-fixed-dim": "var(--c-primary-fixed-dim)",
                        "surface-variant": "var(--c-surface-variant)",
                        "error-container": "var(--c-error-container)",
                        "surface-dim": "var(--c-surface-dim)",
                        "primary-fixed": "var(--c-primary-fixed)",
                        "surface-container": "var(--c-surface-container)"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "xl": "32px",
                        "sm": "12px",
                        "margin-desktop": "28px",
                        "xs": "8px",
                        "md": "16px",
                        "margin-mobile": "16px",
                        "lg": "24px",
                        "base": "4px",
                        "gutter": "16px"
                    },
                    "fontFamily": {
                        "label-sm": ["Inter"],
                        "headline-lg-mobile": ["Manrope"],
                        "body-md": ["Inter"],
                        "body-lg": ["Inter"],
                        "label-xs": ["Inter"],
                        "headline-sm": ["Manrope"],
                        "headline-lg": ["Manrope"],
                        "headline-md": ["Manrope"],
                        "kpi-value": ["Manrope"]
                    },
                    "fontSize": {
                        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
                        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "800" }],
                        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
                        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
                        "label-xs": ["11px", { "lineHeight": "1", "letterSpacing": "0.08em", "fontWeight": "700" }],
                        "headline-sm": ["18px", { "lineHeight": "1.4", "fontWeight": "700" }],
                        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
                        "headline-md": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "700" }],
                        "kpi-value": ["24px", { "lineHeight": "1", "letterSpacing": "-0.03em", "fontWeight": "800" }]
                    }
                }
            }
        }
